apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: scaling-funicular
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:18rc1-bookworm
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
