apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service-deployment
  namespace: scaling-funicular
  labels:
    app: hello-world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
      - name: hello-world-service
        image: scaling-funicular/hello_world_service
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
