apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: scaling-funicular
spec:
  selector:
    app: hello-world-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
